#!/bin/bash
WIZ_REQUIRED_PHP_VERSION="5.2"
WIZ_FOUND_PHP=0

# In case the Path isn't allready set by the User
if [ "" == "$WHIZ_SCRIPT_PATH" ]; then
    SOURCE="${BASH_SOURCE[0]}"
    WIZ_SCRIPT_PATH="$( dirname "$SOURCE" )"

    # If the called File is a Symlink, resolve it
    while [ -h "$SOURCE" ]; do
        SOURCE="$(readlink "$SOURCE")"
        [[ $SOURCE != /* ]] && SOURCE="$WIZ_SCRIPT_PATH/$SOURCE"
        WIZ_SCRIPT_PATH="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
    done

    WIZ_SCRIPT_PATH="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
fi;

if [ "" == "$WIZ_PHP_PATH" ]; then
    IFS=:
    for p in $PATH; do
        if [ -x "$p/php" ]; then
            WIZ_FOUND_PHP=1
            VALID_VERSION=`$p/php -r "echo (int) version_compare(PHP_VERSION, '$WIZ_REQUIRED_PHP_VERSION', '>=');"`
            if [ "1" == "$VALID_VERSION" ]; then
                WIZ_PHP_PATH="$p/php";
                break;
            fi
        fi;
    done
fi

if [ "1" == "$WIZ_FOUND_PHP" -a -z "$WIZ_PHP_PATH" ]; then
    echo "Found a PHP executable, but it's not a version >= $WIZ_REQUIRED_PHP_VERSION.  You can specify one by setting WIZ_PHP_PATH.";
    exit;
elif [ -z "$WIZ_PHP_PATH" ]; then
    echo "Unable to find a PHP >= $WIZ_REQUIRED_PHP_VERSION executable.  You can specify one by setting WIZ_PHP_PATH.";
    exit;
fi

$WIZ_PHP_PATH -f $WIZ_SCRIPT_PATH/wiz.php -- $@

